# Generated by Django 4.0.2 on 2022-03-10 22:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_date_of_birth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Snippet',
        ),
        migrations.AddField(
            model_name='lesson',
            name='attendances',
            field=models.ManyToManyField(related_name='attendances', to=settings.AUTH_USER_MODEL),
        ),
    ]
