# Generated by Django 4.0.2 on 2022-03-12 23:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_snippet_lesson_attendances'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='attendances',
            field=models.ManyToManyField(blank=True, related_name='attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studygroup',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='studying_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studygroup',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='teaching_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
